export const CUISINES = [
        "Afghan",
        "African",
        "American",
        "Arabic",
        "Azerbaijan",
        "Bagels",
        "Bangladeshi",
        "Breakfast",
        "Burgers",
        "Cakes",
        "Caribbean",
        "Chicken",
        "Chinese",
        "Curry",
        "Desserts",
        "English",
        "Ethiopian",
        "Fish & Chips",
        "Greek",
        "Grill",
        "Healthy",
        "Ice Cream",
        "Japanese",
        "Kebab",
        "Korean",
        "Lebanese",
        "Mediterranean",
        "Mexican",
        "Middle Eastern",
        "Milkshakes",
        "Moroccan",
        "Nigerian",
        "Pakistani",
        "Pasta",
        "Peri Peri",
        "Persian",
        "Pick n Mix",
        "Pizza",
        "Polish",
        "Portuguese",
        "Punjabi",
        "Russian",
        "Sandwiches",
        "South Curry",
        "Spanish",
        "Sri-lankan",
        "Sushi",
        "Thai",
        "Turkish",
        "Vegetarian",
        "Vietnamese"
];